=== Gluttton/sidecar/data/sidecar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sidecar">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="info" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="radar" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="riu" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="rib" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="dp" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="version" use="required" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="info">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="comments" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="comments" type="xs:string"/>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="radar">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="gateCountMax"/>
        <xs:element ref="shaftEncodingMax"/>
        <xs:element ref="rotationRate"/>
        <xs:element ref="rangeMin"/>
        <xs:element ref="rangeMax"/>
        <xs:element ref="beamWidth"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="gateCountMax">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="shaftEncodingMax">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="rotationRate">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="rangeMin">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="rangeMax">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="beamWidth">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="riu"/>
  <xs:element name="rib"/>
  <xs:element name="dp">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="host" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="loggerConfigPath" use="optional"/>
      <xs:attribute name="recordingBasePath" use="required"/>
    </xs:complexType>
    <xs:unique name="unique1">
      <xs:selector xpath="host"/>
      <xs:field xpath="name"/>
    </xs:unique>
  </xs:element>
  <xs:element name="host">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="stream" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="tag" use="optional" type="xs:NCName"/>
    </xs:complexType>
    <xs:unique name="unique2">
      <xs:selector xpath="stream"/>
      <xs:field xpath="name"/>
    </xs:unique>
  </xs:element>
  <xs:element name="stream">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="multicast"/>
          <xs:element ref="subscriber"/>
          <xs:element ref="vme"/>
        </xs:choice>
        <xs:element ref="algorithm" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="publisher" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:token"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="algorithm">
    <xs:complexType>
      <xs:sequence>
          <xs:element ref="input" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="output" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="dll" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="optional" type="xs:token"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="multicast">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="output" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="host" use="required" type="xs:NCName"/>
      <xs:attribute name="port" use="required" type="xs:unsignedShort"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="publisher">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="input" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="subscriber">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="output" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:token"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="vme">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="output" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="interface" use="required" type="xs:NCName"/>
      <xs:attribute name="port" use="required" type="xs:unsignedShort"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="input">
    <xs:complexType>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="optional" type="xs:token"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="output">
    <xs:complexType>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="optional" type="xs:token"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="param">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:token"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
      <xs:attribute name="value" use="required" type="xs:token"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Gluttton/sidecar/data/configs/TSPI.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Valid elements within the <sidecar> element are:
     info - configuration file description
     radar - settings of the radar
     riu - configuration for the RIU (VME system)
     rib - configuration for the RIB control system
     dp - configuration for the data processing / recording system

     All SideCar processes will receive the same file, but they should just
     ignore the elements that they do not recognize or need.
  -->
<sidecar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="sidecar.xsd" version="1.0">

  <!-- Information about the configuration file 
       name - display name
       comments - commentary describing the configuration
    -->
  <info>
    <name>Foobar</name>
    <comments>
      Contains algorithm chain for basic extraction from NegativeVideo channel.
      The data-recorder only runs algorithms for data conversion from VME host.
    </comments>
  </info>

  <!-- Information about the radar being monitored
       name - radar name (needed?)
       rotationRate - number of rotations per minute
       beamWidth - how far the radar rotates while sampling one PRI (radians)
       shaftEncodingMax - the maximum shaft encoding value to expect
       gatesPerMessage - the maximum number of samples to expect in a PRI
       message
       rangeOfFirstGate - the range value associated with the first sample
       rangeDelta - the change in range between subsequent samples
    -->
  <radar file="/opt/sidecar/data/radar-1.xml"  />

  <!-- Configuration of the Radar Interface Unit (RIU) VME system
    -->
  <riu> </riu>

  <!-- Configuration of the Radar Interface Box (RIB) PC-104 system.
    -->
  <rib> </rib>

  <!-- Configuration for the Data Processing (DP) DELL Blade systems. Contains
       host-specific items inside <host> tags. Note that this may also apply to
       the Data Recorder box if there is a <host> element with the name
       'data-recorder'

       The only valid element inside <dp> is <host>
    -->
  <dp recordingsDirectory="/space1/recordings">
    <runner name="TSPI Reader" host="blade-1" multicast="237.1.2.101">
      <stream name="TSPI Reader">
	<tspi host="237.1.2.123" port="5000"/>
	<algorithm dll="TSPI">
	  <input type="TSPI"/>
	  <output type="TSPI"/>
	  <param name="recordingEnabled" type="boolean" value="1"/>
	</algorithm>
	<publisher name="TSPI Plots" type="TSPI"/>
      </stream>
    </runner>
  </dp>

</sidecar>
