=== Gluttton/sidecar/data/sidecar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sidecar">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="info" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="radar" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="riu" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="rib" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="dp" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="version" use="required" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="info">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="comments" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="comments" type="xs:string"/>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="radar">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="gateCountMax"/>
        <xs:element ref="shaftEncodingMax"/>
        <xs:element ref="rotationRate"/>
        <xs:element ref="rangeMin"/>
        <xs:element ref="rangeMax"/>
        <xs:element ref="beamWidth"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="gateCountMax">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="shaftEncodingMax">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="rotationRate">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="rangeMin">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="rangeMax">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="beamWidth">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="riu"/>
  <xs:element name="rib"/>
  <xs:element name="dp">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="host" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="loggerConfigPath" use="optional"/>
      <xs:attribute name="recordingBasePath" use="required"/>
    </xs:complexType>
    <xs:unique name="unique1">
      <xs:selector xpath="host"/>
      <xs:field xpath="name"/>
    </xs:unique>
  </xs:element>
  <xs:element name="host">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="stream" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="tag" use="optional" type="xs:NCName"/>
    </xs:complexType>
    <xs:unique name="unique2">
      <xs:selector xpath="stream"/>
      <xs:field xpath="name"/>
    </xs:unique>
  </xs:element>
  <xs:element name="stream">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="multicast"/>
          <xs:element ref="subscriber"/>
          <xs:element ref="vme"/>
        </xs:choice>
        <xs:element ref="algorithm" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="publisher" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:token"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="algorithm">
    <xs:complexType>
      <xs:sequence>
          <xs:element ref="input" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="output" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="dll" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="optional" type="xs:token"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="multicast">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="output" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="host" use="required" type="xs:NCName"/>
      <xs:attribute name="port" use="required" type="xs:unsignedShort"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="publisher">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="input" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="subscriber">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="output" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:token"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="vme">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="output" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="interface" use="required" type="xs:NCName"/>
      <xs:attribute name="port" use="required" type="xs:unsignedShort"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="input">
    <xs:complexType>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="optional" type="xs:token"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="output">
    <xs:complexType>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="optional" type="xs:token"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="param">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:token"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
      <xs:attribute name="value" use="required" type="xs:token"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Gluttton/sidecar/data/configs/data_converters.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Valid elements within the <sidecar> element are:
     info - configuration file description
     radar - settings of the radar
     riu - configuration for the RIU (VME system)
     rib - configuration for the RIB control system
     dp - configuration for the data processing / recording system

     All SideCar processes will receive the same file, but they should just
     ignore the elements that they do not recognize or need.
  -->
<sidecar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="sidecar.xsd" version="1.0">

  <!-- Information about the configuration file 
       name - display name
       comments - commentary describing the configuration
    -->
  <info>
    <name>Sidecar Configuration 1.0.0 (DEV)</name>
    <comments>
      blah, blah, blah
    </comments>
  </info>

  <radar file="/opt/sidecar/data/configs/radar-1.xml"/>

  <!-- Configuration of the Radar Interface Unit (RIU) VME system
    -->
  <riu> </riu>

  <!-- Configuration of the Radar Interface Box (RIB) PC-104 system.
    -->
  <rib> </rib>

  <!-- Configuration for the Data Processing (DP) DELL Blade systems. Contains
       host-specific items inside <host> tags. Note that this may also apply to
       the Data Recorder box if there is a <host> element with the name
       'data-recorder'

       The only valid element inside <dp> is <host>
    -->
  <dp recordingBasePath="/space1/recordings"
      loggerConfigPath="/opt/sidecar/builds/latest/data/logger.cfg">

    <!-- Configuration sample for a runner named 'sample.' The only valid
	 element in <runner> is <stream>. Each stream is made up of one or
	 more tasks with the following element names:

	 - vme: VME UDP connection
	 - multicast: VME Multicast UDP connection
	 - filein: message source that takes data from a file
	 - fileout: message sink that writes data to a file
	 - subscriber: message source that obtains data from a remote publisher
	 - publisher: message sink that publishes data to remote subscribers
	 - algorithm: a processing algorithm which may have one or more runtime
   	   parameter settings (<param> elements)
      -->

    <!-- BEGIN blade-1 configuration -->
    <runner host="blade-1" name="Data Converter 1" 
	    multicast="237.1.2.101">
      <stream name="NegativeVideo Converter">
	<vme host="237.1.10.1" port="5014"/>
	<algorithm dll="RawPRI" name="NegativeVideo">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="NegativeVideo" type="Video"/>
      </stream>
      <stream name="BiPolarVideo Converter">
	<vme host="237.1.10.1" port="5015"/>
	<algorithm dll="RawPRI" name="BiPolarVideo">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="BiPolarVideo" type="Video"/>
      </stream>
      <stream name="CompositeVideo Converter">
	<vme host="237.1.10.1" port="5016"/>
	<algorithm dll="RawPRI" name="CompositeVideo">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="CompositeVideo" type="Video"/>
      </stream>
      <stream name="RadarDisplay Converter">
	<vme host="237.1.10.1" port="5017"/>
	<algorithm dll="RawPRI" name="RadarDisplay">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="RadarDisplay" type="Video"/>
      </stream>
    </runner> 
    <!-- end Channel Conversion (1) runner -->

    <runner host="blade-1" name="Data Converter 2" 
	    multicast="237.1.2.101"> 
      <stream name="RxIF Converter">
	<vme host="237.1.10.2" port="5018"/>
	<algorithm dll="RawPRI" name="RxIF">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="RxIF" type="Video"/>
      </stream>
      <stream name="Coho Converter">
	<vme host="237.1.10.2" port="5019"/>
	<algorithm dll="RawPRI" name="Coho">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="Coho" type="Video"/>
      </stream>
      <stream name="RxRF Converter">
	<vme host="237.1.10.2" port="5020"/>
	<algorithm dll="RawPRI" name="RxRF">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="RxRF" type="Video"/>
      </stream>
      <stream name="TxRF Converter">
	<vme host="237.1.10.2" port="5021"/>
	<algorithm dll="RawPRI" name="TxRF">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="TxRF" type="Video"/>
      </stream>
    </runner> 
    <!-- end Channel Conversion (2) runner -->

    <runner host="blade-1" name="Data Converter 3" 
	    multicast="237.1.2.101">
      <stream name="AUX1 Converter">
	<vme host="237.1.10.3" port="5022"/>
	<algorithm dll="RawPRI" name="AUX1">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="AUX1" type="Video"/>
      </stream>
      <stream name="AUX2 Converter">
	<vme host="237.1.10.3" port="5023"/>
	<algorithm dll="RawPRI" name="AUX2">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="AUX2" type="Video"/>
      </stream>
      <stream name="AUX3 Converter">
	<vme host="237.1.10.3" port="5024"/>
	<algorithm dll="RawPRI" name="AUX3">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="AUX3" type="Video"/>
      </stream>
      <stream name="AUX4 Converter">
	<vme host="237.1.10.3" port="5025"/>
	<algorithm dll="RawPRI" name="AUX4">
	  <input type="RawVideo"/>
	  <output type="Video"/>
	</algorithm>
	<publisher name="AUX4" type="Video"/>
      </stream>
    </runner>
    <!-- end Channel Conversion (3) runner -->
  
  </dp>

</sidecar>

=== Gluttton/sidecar/data/configs/BugCollector.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Valid elements within the <sidecar> element are:
     info - configuration file description
     radar - settings of the radar
     riu - configuration for the RIU (VME system)
     rib - configuration for the RIB control system
     dp - configuration for the data processing / recording system

     All SideCar processes will receive the same file, but they should just
     ignore the elements that they do not recognize or need.
  -->
<sidecar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="sidecar.xsd" version="1.0">

  <!-- Information about the configuration file 
       name - display name
       comments - commentary describing the configuration
    -->
  <info>
    <name>Foobar</name>
    <comments>
      Contains algorithm chain for basic extraction from NegativeVideo channel.
      The data-recorder only runs algorithms for data conversion from VME host.
    </comments>
  </info>

  <!-- Information about the radar being monitored
       name - radar name (needed?)
       rotationRate - number of rotations per minute
       beamWidth - how far the radar rotates while sampling one PRI (radians)
       shaftEncodingMax - the maximum shaft encoding value to expect
       gatesPerMessage - the maximum number of samples to expect in a PRI
       message
       rangeOfFirstGate - the range value associated with the first sample
       rangeDelta - the change in range between subsequent samples
    -->
  <radar>
    <name>Radar</name>
    <gateCountMax type="int">4684</gateCountMax>
    <shaftEncodingMax type="int">65535</shaftEncodingMax>
    <rotationRate units="rpm" type="double">6</rotationRate>
    <rangeMin units="km" type="double">0.0</rangeMin>
    <rangeMax units="km" type="double">300.0</rangeMax>
    <beamWidth units="radians" type="double">0.00125644</beamWidth>
  </radar>

  <!-- Configuration of the Radar Interface Unit (RIU) VME system
    -->
  <riu> </riu>

  <!-- Configuration of the Radar Interface Box (RIB) PC-104 system.
    -->
  <rib> </rib>

  <!-- Configuration for the Data Processing (DP) DELL Blade systems. Contains
       host-specific items inside <host> tags. Note that this may also apply to
       the Data Recorder box if there is a <host> element with the name
       'data-recorder'

       The only valid element inside <dp> is <host>
    -->
  <dp recordingsDirectory="/Users/howes/tmp"
      loggerConfiguration="/opt/sidecar/builds/latest/data/logger.cfg"
      logsDirectory="/tmp">
    <runner name="BugCollector" host="tomcat.local" multicast="237.1.2.103">
      <stream name="BugCollector Stream">
	<algorithm dll="BugCollector">
	  <param name="prefix" type="string" value="UserBugs"/>
	  <output type="BugPlot"/>
	</algorithm>
	<publisher name="Bug Collector" type="BugPlot"/>
      </stream>
    </runner>
  </dp>
</sidecar>

=== Gluttton/sidecar/data/configs/basic.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Valid elements within the <sidecar> element are:
     info - configuration file description
     radar - settings of the radar
     riu - configuration for the RIU (VME system)
     rib - configuration for the RIB control system
     dp - configuration for the data processing / recording system

     All SideCar processes will receive the same file, but they should just
     ignore the elements that they do not recognize or need.
  -->
<sidecar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="sidecar.xsd" version="1.0">

  <!-- Information about the configuration file 
       name - display name
       comments - commentary describing the configuration
    -->
  <info>
    <name>Basic Extraction</name>
    <comments>
      Contains algorithm chain for basic extraction from NegativeVideo channel.
      The data-recorder only runs algorithms for data conversion from VME host.
    </comments>
  </info>

  <!-- Information about the radar being monitored
       name - radar name (needed?)
       rotationRate - number of rotations per minute
       beamWidth - how far the radar rotates while sampling one PRI (radians)
       shaftEncodingMax - the maximum shaft encoding value to expect
       gatesPerMessage - the maximum number of samples to expect in a PRI
       message
       rangeOfFirstGate - the range value associated with the first sample
       rangeDelta - the change in range between subsequent samples
    -->
  <radar file="radar-1.xml"/>

  <!-- Configuration of the Radar Interface Unit (RIU) VME system
    -->
  <riu> </riu>

  <!-- Configuration of the Radar Interface Box (RIB) PC-104 system.
    -->
  <rib> </rib>

  <!-- Configuration for the Data Processing (DP) DELL Blade systems. Contains
       host-specific items inside <host> tags. Note that this may also apply to
       the Data Recorder box if there is a <host> element with the name
       'data-recorder'

       The only valid element inside <dp> is <host>
    -->
  <dp recordingBasePath="/Users/howes/sidecar/recordings" loggerConfigPath="/opt/sidecar/data/logger.cfg">
    <runner name="localhost" tag="1" multicast="237.1.2.102">

      <!-- Basic target extraction processing stream -->

      <stream name="BasicExtraction">

	<subscriber name="NegativeVideo" type="Video"/>
	<algorithm dll="NCIntegrate">
	  <input type="Video"/>
	  <output type="Video" channel="NCIntegrate"/>
	</algorithm>

        <publisher name="NCIntegrate" type="Video" channel="NCIntegrate"/>

	<algorithm dll="Threshold">
	  <input type="Video" channel="NCIntegrate"/>
	  <output type="BinaryVideo" channel="Threshold"/>
	  <param name="threshold" type="int" value="-2400"/>
	</algorithm>

        <publisher name="Threshold" type="BinaryVideo" channel="Threshold"/>

        <algorithm dll="MofN">
	  <input type="BinaryVideo" channel="Threshold"/>
	  <output type="BinaryVideo" channel="MofN"/>
	</algorithm>

        <publisher name="MofN" type="BinaryVideo" channel="MofN"/>

        <algorithm dll="Extract">
	  <input type="BinaryVideo" channel="MofN"/>
	  <output type="Extractions" channel="Extract"/>
	</algorithm>

        <publisher name="Extractions" type="Extractions" channel="Extract"/>

      </stream>
    </runner>
  </dp>

</sidecar>

=== Gluttton/sidecar/data/configs/proposedTracker.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Valid elements within the <sidecar> element are:
     info - configuration file description
     radar - settings of the radar
     riu - configuration for the RIU (VME system)
     rib - configuration for the RIB control system
     dp - configuration for the data processing / recording system

     All SideCar processes will receive the same file, but they should just
     ignore the elements that they do not recognize or need.
  -->
<sidecar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="sidecar.xsd" version="1.0">

  <!-- Information about the configuration file 
       name - display name
       comments - commentary describing the configuration
    -->
  <info>
    <name>Sidecar Configuration 1.0.0 (DEV)</name>
    <comments>
  
    </comments>
  </info>

  <!-- Information about the radar being monitored
       name - radar name (needed?)
       rotationRate - number of rotations per minute
       beamWidth - how far the radar rotates while sampling one PRI (radians)
       shaftEncodingMax - the maximum shaft encoding value to expect
       gatesPerMessage - the maximum number of samples to expect in a PRI
       message
       rangeOfFirstGate - the range value associated with the first sample
       rangeDelta - the change in range between subsequent samples
    -->
  <radar>
    <name>Radar</name>
    <gateCountMax type="int">4684</gateCountMax>
    <shaftEncodingMax type="int">65535</shaftEncodingMax>
    <rotationRate units="rpm" type="double">6</rotationRate>
    <rangeMin units="km" type="double">0.0</rangeMin>
    <rangeMax units="km" type="double">300.0</rangeMax>
    <beamWidth units="radians" type="double">0.00125644</beamWidth>
    <latitude units="degrees" type="double">0.0</latitude>
    <longitude units="degrees" type="double">0.0</longitude>
    <height units="meters" type="double">0.0</height>
  </radar>

  <!-- Configuration of the Radar Interface Unit (RIU) VME system
    -->
  <riu> </riu>

  <!-- Configuration of the Radar Interface Box (RIB) PC-104 system.
    -->
  <rib> </rib>

  <!-- Configuration for the Data Processing (DP) DELL Blade systems. Contains
       host-specific items inside <host> tags. Note that this may also apply to
       the Data Recorder box if there is a <host> element with the name
       'data-recorder'

       The only valid element inside <dp> is <host>
    -->
  <dp recordingsDirectory="/tmp"
      loggerConfiguration="/opt/sidecar/builds/latest/data/logger.cfg">

    <!-- Configuration sample for a runner named 'sample.' The only valid
	 element in <runner> is <stream>. Each stream is made up of one or
	 more tasks with the following element names:

	 - vme: VME UDP connection
	 - multicast: VME Multicast UDP connection
	 - filein: message source that takes data from a file
	 - fileout: message sink that writes data to a file
	 - subscriber: message source that obtains data from a remote publisher
	 - publisher: message sink that publishes data to remote subscribers
	 - algorithm: a processing algorithm which may have one or more runtime
   	   parameter settings (<param> elements)
      -->
    
    <runner host="blade-1" name="Tracker" multicast="237.1.2.102">

      <stream name="Tracker">
    
       <subscriber name="track_maintainer_output" type="Track" channel="track_status_updates"/>
       <subscriber name="state_estimator_output" type="Track" channel="new_state_info"/>
       <subscriber name="track_initiator_output" type="Track" channel="new_tracks"/>
    
                <algorithm dll="ComposeExtractions">
                   <output type="Extractions" channel="ComposeExtractionsOut"/>                
                </algorithm>
    
        	<algorithm dll="DataAssociation">
        	  <input type="Extractions" name="extractions" channel="ComposeExtractionsOut"/>
        	  <input type="Track" name="track_status_updates" channel="track_status_updates"/>
                  <input type="Track" name="new_state_info" channel="new_state_info"/>
                  <input type="Track" name="new_tracks" channel="new_tracks"/>

        	  <output type="Extractions" name="unassoc_extractions" channel="unassoc_extractions"/>
                  <output type="Track" name="for_state_estimator" channel="for_state_estimator"/>
                  <output type="Track" name="corrected" channel="corrected"/>
        	  <param name="gateSizeMeters" type="int" value="2000"/>
                  <param name="secsPerProcessingSector" type="int" value="1"/>
                  <param name="assumedAltitude" type="double" value="7620.0"/>
                  <param name="alwaysUsingData" type="boolean" value="1"/>
        	</algorithm>

        	<algorithm dll="TrackInitiator">
        	  <input type="Extractions" channel="unassoc_extractions"/>
        	  <output type="Track" name="track_initiator_output" channel="track_initiator_output"/>
                  <param name="numScans" type="int" value="2"/>
                  <param name="searchRadius" type="double" value="5.0"/>
                  <param name="minRange" type="double" value="10.0" />
                  <param name="assumedAltitude" type="double" value="7620.0"/>
                  <param name="alwaysUsingData" type="boolean" value="1"/>
        	</algorithm>

                <publisher name="track_initiator_output" type="Track" channel="track_initiator_output"/>

        	<algorithm dll="StateEstimatorAB" name="StateEstimatorAB">
        	  <input type="Track" channel="for_state_estimator"/>
        	  <output type="Track" name="state_estimator_output" channel="state_estimator_output"/>
                  <param name="alpha" type="double" value="0.5"/>
                  <param name="beta" type="double" value="0.5"/>
                  <param name="assumedAltitude" type="double" value="7620.0"/>
                  <param name="alwaysUsingData" type="boolean" value="1"/>
        	</algorithm>        

                <publisher name="state_estimator_output" type="Track" channel="state_estimator_output"/>

                <algorithm dll="TrackMaintainer">
        	  <input type="Track" channel="corrected"/>
        	  <output type="Track" name="track_maintainer_output" channel="track_maintainer_output"/>
                  <param name="hitsBeforePromote" type="int" value="3"/>
                  <param name="missesBeforeDrop" type="int" value="3"/>
                  <param name="alwaysUsingData" type="boolean" value="1"/>
        	</algorithm>        
                
                <publisher name="track_maintainer_output" type="Track" channel="track_maintainer_output"/>


      </stream>

  

    </runner>

  </dp>

</sidecar>

=== Gluttton/sidecar/data/configs/noop.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Valid elements within the <sidecar> element are:
     info - configuration file description
     radar - settings of the radar
     riu - configuration for the RIU (VME system)
     rib - configuration for the RIB control system
     dp - configuration for the data processing / recording system

     All SideCar processes will receive the same file, but they should just
     ignore the elements that they do not recognize or need.
  -->
<sidecar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="sidecar.xsd" version="1.0">

  <!-- Information about the configuration file 
       name - display name
       comments - commentary describing the configuration
    -->
  <info>
    <name>Sidecar Configuration 1.0.0 (DEV)</name>
    <comments>
      
    </comments>
  </info>

  <!-- Information about the radar being monitored
       name - radar name (needed?)
       rotationRate - number of rotations per minute
       beamWidth - how far the radar rotates while sampling one PRI (radians)
       shaftEncodingMax - the maximum shaft encoding value to expect
       gatesPerMessage - the maximum number of samples to expect in a PRI
       message
       rangeOfFirstGate - the range value associated with the first sample
       rangeDelta - the change in range between subsequent samples
    -->
  <radar>
    <name>Radar</name>
    <gateCountMax type="int">4684</gateCountMax>
    <shaftEncodingMax type="int">65535</shaftEncodingMax>
    <rotationRate units="rpm" type="double">6</rotationRate>
    <rangeMin units="km" type="double">0.0</rangeMin>
    <rangeMax units="km" type="double">300.0</rangeMax>
    <beamWidth units="radians" type="double">0.00125644</beamWidth>
  </radar>

  <!-- Configuration of the Radar Interface Unit (RIU) VME system
    -->
  <riu> </riu>

  <!-- Configuration of the Radar Interface Box (RIB) PC-104 system.
    -->
  <rib> </rib>

  <!-- Configuration for the Data Processing (DP) DELL Blade systems. Contains
       host-specific items inside <host> tags. Note that this may also apply to
       the Data Recorder box if there is a <host> element with the name
       'data-recorder'

       The only valid element inside <dp> is <host>
    -->
  <dp recordingsDirectory="/space1/recordings"
      loggerConfiguration="/opt/sidecar/data/logger.cfg">

    <!-- Configuration sample for a runner named 'sample.' The only valid
	 element in <runner> is <stream>. Each stream is made up of one or
	 more tasks with the following element names:

	 - vme: VME UDP connection
	 - multicast: VME Multicast UDP connection
	 - filein: message source that takes data from a file
	 - fileout: message sink that writes data to a file
	 - subscriber: message source that obtains data from a remote publisher
	 - publisher: message sink that publishes data to remote subscribers
	 - algorithm: a processing algorithm which may have one or more runtime
   	   parameter settings (<param> elements)
      -->

    <runner host="localhost" name="NOOP" multicast="237.1.2.104">
      <stream name="NOOP">
	<subscriber name="TxRF" type="Video" channel="input"/>
	<algorithm dll="SimpleNOOP">
	  <input type="Video" channel="input"/>
	  <output type="Video" channel="noop"/>
	  <param name="alwaysUsingData" type="boolean" value="1"/>
	</algorithm>
	<publisher name="NOOPout" type="Video" channel="noop"/>
      </stream>
    </runner>
    <!-- end Side Lobe Canceler runner -->

  </dp>

</sidecar>
